let cards=[];
const cardsReady=(location.protocol==='file:'?Promise.resolve(window.FAKE_PAINTER_CARDS):fetch('data/cards.json').then(response=>{
 if(!response.ok)throw new Error(`无法读取画卡数据（HTTP ${response.status}）`);
 return response.json();
})).then(data=>{cards=data;return cards}).catch(error=>{console.error('画卡数据加载失败',error);throw error});
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="fullscreen.css"><link rel="stylesheet" href="discard.css">');
const $=s=>document.querySelector(s);let state={card:null,seconds:90,selectedTime:90,running:false,timeLocked:false,criterion:0,score:0,interval:null,endTime:null,pauseRemainingTime:90,ended:false};
const discardedCardIds=new Set();
function show(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#screen-'+name).classList.add('active');$('#phase-label').textContent={home:'准备开局',rules:'玩法说明',prepare:'抽取画卡',draw:'描述与作画',score:'评分揭晓',result:'本轮结算'}[name]||''}
function goHome(){stopTimer();state.running=false;state.endTime=null;if($('#fullscreen-viewer'))$('#fullscreen-viewer').classList.add('hidden');show('home')}
async function pick(){try{await cardsReady;const availableCards=cards.filter(card=>!discardedCardIds.has(card.id));if(!availableCards.length){showExhausted();return false}stopTimer();state.card=availableCards[Math.floor(Math.random()*availableCards.length)];state.selectedTime=state.card.timer;state.seconds=state.selectedTime;state.pauseRemainingTime=state.selectedTime;state.criterion=0;state.score=0;state.running=false;state.timeLocked=false;state.endTime=null;state.ended=false;$('#card-image').src=state.card.image;$('#score-image').src=state.card.image;renderTimer();renderTimeSettings();$('#art-cover').classList.remove('hidden');$('#to-score').classList.add('hidden');$('#timer-toggle').textContent='开始';hideDiscardNotice();show('draw');return true}catch(error){console.error('无法抽取画卡',error);return false}}
function showExhausted(){stopTimer();state.card=null;$('#discard-notice').classList.remove('hidden');$('#art-cover').classList.remove('hidden');$('#to-score').classList.add('hidden');$('#timer-toggle').disabled=true;$('#discard-card').disabled=true;show('draw')}
function hideDiscardNotice(){if($('#discard-notice'))$('#discard-notice').classList.add('hidden');if($('#timer-toggle'))$('#timer-toggle').disabled=false;if($('#discard-card'))$('#discard-card').disabled=false}
function discardCurrentCard(){if(!state.card)return;discardedCardIds.add(state.card.id);stopTimer();state.running=false;state.endTime=null;pick()}
function resetDiscardedCards(){discardedCardIds.clear();pick()}
function renderTimer(){const m=String(Math.floor(state.seconds/60)).padStart(2,'0'),s=String(state.seconds%60).padStart(2,'0');$('#timer').textContent=`${m}:${s}`;$('#timer').classList.toggle('danger',state.seconds<=10)}
function renderTimeSettings(){const locked=state.timeLocked||state.running||state.ended;$('#time-settings').classList.toggle('locked',locked);document.querySelectorAll('.time-preset[data-time]').forEach(button=>button.classList.toggle('selected',Number(button.dataset.time)===state.selectedTime));$('#custom-minutes').value=Math.floor(state.selectedTime/60);$('#custom-seconds').value=state.selectedTime%60}
function setTime(seconds){if(state.timeLocked||state.running||state.ended)return;const safe=Math.max(1,Math.min(5999,Math.round(seconds)));state.selectedTime=safe;state.seconds=safe;state.pauseRemainingTime=safe;renderTimer();renderTimeSettings()}
function applyCustomTime(){const minutes=Math.max(0,Math.min(99,Number($('#custom-minutes').value)||0));const seconds=Math.max(0,Math.min(59,Number($('#custom-seconds').value)||0));setTime(minutes*60+seconds)}
function stopTimer(){if(state.interval!==null){clearInterval(state.interval);state.interval=null}}
function finishTimer(){if(state.ended)return;state.ended=true;state.seconds=0;state.pauseRemainingTime=0;state.running=false;stopTimer();$('#fullscreen-viewer')?.closeViewer?.();renderTimer();$('#timer-toggle').textContent='时间到';$('#art-cover').classList.remove('hidden');$('#fullscreen-viewer')?.updateAvailability?.();$('#to-score').classList.remove('hidden');beep()}
function refreshTimer(){if(!state.running||state.endTime===null)return;const remainingMs=state.endTime-Date.now();if(remainingMs<=0){finishTimer();return}state.seconds=Math.max(0,Math.ceil(remainingMs/1000));state.pauseRemainingTime=state.seconds;renderTimer()}
function toggleTimer(){if(state.ended||!state.card)return;if(state.running){refreshTimer();if(state.ended)return;state.pauseRemainingTime=state.seconds;state.running=false;state.endTime=null;stopTimer();$('#timer-toggle').textContent='继续';return}if(state.pauseRemainingTime<=0)return;state.timeLocked=true;state.endTime=Date.now()+state.pauseRemainingTime*1000;state.running=true;$('#timer-toggle').textContent='暂停';renderTimeSettings();$('#art-cover').classList.add('hidden');$('#fullscreen-viewer')?.updateAvailability?.();refreshTimer();if(state.running)state.interval=setInterval(refreshTimer,100)}
function beep(){try{const c=new AudioContext(),now=c.currentTime;for(let i=0;i<10;i++){const o=c.createOscillator(),g=c.createGain(),start=now+i*.95;o.type='sine';o.frequency.setValueAtTime(i%2?660:520,start);g.gain.setValueAtTime(.4,start);g.gain.exponentialRampToValueAtTime(.001,start+.35);o.connect(g);g.connect(c.destination);o.start(start);o.stop(start+.36)}}catch(e){}}
function resetTimer(){if(!state.card)return;stopTimer();state.seconds=state.selectedTime;state.pauseRemainingTime=state.selectedTime;state.running=false;state.timeLocked=false;state.endTime=null;state.ended=false;$('#timer-toggle').textContent='开始';$('#art-cover').classList.remove('hidden');$('#fullscreen-viewer')?.updateAvailability?.();renderTimer();renderTimeSettings()}
function setupDiscardControls(){const actions=document.querySelector('.draw-layout .actions');if(!actions||$('#discard-card'))return;const button=document.createElement('button');button.className='button ghost full';button.id='discard-card';button.dataset.action='discard-card';button.textContent='换一张 / 弃掉此卡';actions.parentElement.insertBefore(button,actions.nextSibling);const notice=document.createElement('div');notice.id='discard-notice';notice.className='discard-notice hidden';notice.innerHTML='<strong>本轮画卡已全部用完，请重新开始游戏。</strong><button class="button ghost" data-action="reset-discarded">重置画卡池</button>';actions.parentElement.insertBefore(notice,button.nextSibling)}
function setupFullscreen(){
 const artCard=$('.art-card');if(!artCard||$('#fullscreen-viewer'))return;
 const open=document.createElement('button');open.className='fullscreen-open hidden';open.dataset.action='fullscreen-open';open.textContent='全屏查看';open.setAttribute('aria-label','全屏查看画卡');artCard.append(open);
 const viewer=document.createElement('div');viewer.id='fullscreen-viewer';viewer.className='fullscreen-viewer hidden';viewer.innerHTML='<div class="fullscreen-actions"><button class="fullscreen-orient" data-action="fullscreen-orient">横屏查看</button><button class="fullscreen-close" data-action="fullscreen-close" aria-label="关闭全屏">×</button></div><img id="fullscreen-image" alt="放大查看画卡">';document.body.append(viewer);
 const image=$('#fullscreen-image');let scale=1,x=0,y=0,gesture=null,pan=null;
 function render(){if(scale===1){x=0;y=0}image.style.transform=`translate3d(${x}px,${y}px,0) scale(${scale})`}
 function distance(a,b){return Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY)}
 function center(a,b){return{x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2}}
 function updateAvailability(){const visible=!!state.card&&state.running&&$('#art-cover').classList.contains('hidden');open.classList.toggle('hidden',!visible);open.disabled=!visible}
 function openViewer(){if(open.disabled)return;image.src=$('#card-image').src;scale=1;x=0;y=0;render();viewer.classList.remove('hidden')}
 async function orientViewer(){try{if(screen.orientation?.lock){await screen.orientation.lock('landscape');return}throw new Error('unsupported')}catch(e){alert('请旋转手机横屏查看')}}
 function closeViewer(){viewer.classList.add('hidden');gesture=pan=null;try{screen.orientation?.unlock?.()}catch(e){}}
 openViewer.close=closeViewer;viewer.openViewer=openViewer;viewer.closeViewer=closeViewer;viewer.orientViewer=orientViewer;viewer.addEventListener('wheel',e=>{e.preventDefault();scale=Math.min(5,Math.max(1,scale+(e.deltaY<0?.25:-.25)));render()},{passive:false});
 viewer.addEventListener('touchstart',e=>{if(e.touches.length===2){const c=center(e.touches[0],e.touches[1]);gesture={distance:distance(e.touches[0],e.touches[1]),scale,x,y,cx:c.x,cy:c.y};pan=null}else if(e.touches.length===1&&scale>1){pan={x:e.touches[0].clientX-x,y:e.touches[0].clientY-y}}},{passive:false});
 viewer.addEventListener('touchmove',e=>{if(e.touches.length===2&&gesture){e.preventDefault();const d=distance(e.touches[0],e.touches[1]),c=center(e.touches[0],e.touches[1]);scale=Math.min(5,Math.max(1,gesture.scale*d/gesture.distance));x=gesture.x+(c.x-gesture.cx);y=gesture.y+(c.y-gesture.cy);render()}else if(e.touches.length===1&&pan){e.preventDefault();x=e.touches[0].clientX-pan.x;y=e.touches[0].clientY-pan.y;render()}},{passive:false});
 viewer.addEventListener('touchend',e=>{if(e.touches.length<2)gesture=null;if(e.touches.length===0)pan=null;render()});
 viewer.addEventListener('touchcancel',()=>{gesture=pan=null;render()});
 viewer.updateAvailability=updateAvailability;updateAvailability();
}function startScore(){clearInterval(state.interval);state.criterion=0;state.score=0;$('#score-number').textContent='0';renderCriterion();show('score')}
function renderCriterion(){const i=state.criterion;$('#criterion-count').textContent=`第 ${i+1} 条 / 10`;$('#criterion-text').textContent=state.card.criteria[i]}
function answer(hit){if(hit)state.score++;state.criterion++;if(state.criterion>=10){$('#final-score').textContent=state.score;$('#result-copy').textContent=state.score>=7?'真迹级别！艺术总监慧眼如炬。':state.score>=4?'不错的观察力，下一幅继续挑战。':'赝品画师成功混入，下一轮扳回一城。';show('result')}else renderCriterion()}
 setupDiscardControls();setupFullscreen();document.addEventListener('click',e=>{const a=e.target.dataset.action;if(a==='time-preset')setTime(Number(e.target.dataset.time));if(a==='custom-time'){document.querySelector('.custom-time').scrollIntoView({behavior:'smooth',block:'nearest'});$('#custom-minutes').focus()}if(a==='apply-custom')applyCustomTime();if(a==='discard-card')discardCurrentCard();if(a==='reset-discarded')resetDiscardedCards();if(a==='fullscreen-open'&&state.running&&$('#art-cover').classList.contains('hidden'))$('#fullscreen-viewer').openViewer?.();if(a==='fullscreen-close')$('#fullscreen-viewer').closeViewer?.();if(a==='fullscreen-orient')$('#fullscreen-viewer').orientViewer?.();if(a==='start'||a==='again')show('prepare');if(a==='home')goHome();if(a==='rules')show('rules');if(a==='reveal-card')pick();if(a==='toggle-timer')toggleTimer();if(a==='reset-timer')resetTimer();if(a==='score')startScore();if(a==='hit')answer(true);if(a==='miss')answer(false)});
